### ISSUE TITLE
Not working on kali linux 2018

### ISSUE THREAD

**Issue by kofa2002** [urbanesec/ZackAttack#65]
Traceback (most recent call last):
	19: from zackattack.rb:8:in `<main>'
	18: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	17: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	16: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	15: from /root/ZackAttack/lib/zfhttpd.rb:7:in `<top (required)>'
	14: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	13: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	12: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	11: from /root/ZackAttack/lib/zfclient.rb:6:in `<top (required)>'
	10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	 8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	 7: from /root/ZackAttack/clients/ews.rb:9:in `<top (required)>'
	 6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	 5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	 4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	 3: from /root/ZackAttack/lib/zfdb.rb:7:in `<top (required)>'
	 2: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	 1: from /usr/lib/ruby/2.5.0/rubygems/dependency.rb:322:in `to_spec'
/usr/lib/ruby/2.5.0/rubygems/dependency.rb:312:in `to_specs': Could not find 'sqlite3' (= 1.3.6) - did find: [sqlite3-1.3.13,sqlite3-1.3.9] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.5.0:/var/lib/gems/2.5.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all', execute `gem env` for more information

**Comment by YoshiRulz** [comment]
This project hasn't received a commit in six years and was never ported to Ruby 2.x, so your chances of a fix aren't looking too good.
